### ISSUE TITLE
Avoid channels to get copied

### ISSUE THREAD

**Issue by gdb88** [glizzykingdreko/DiscordWizard#4]
More than an issue is a request. Sorry not a coder so first of all thank you for the great work because it works like a charm.

Now what I see is that many times I dont really want to copy the whole structure of the discord server, but just some channels that I might be interested in. Is there a way to accomplish this with your code?

And sorry if this is not the correct place to post this. First time using github. Just created an account to post this.

Thank you in advance!

**Comment by glizzykingdreko** [comment]
You wanna make the ids of the excluded challels into the `settings.yaml `like this

```yaml
client:
  token: "Nj..."
  server_id: 1071...
  excluded_channels:
    - 000000001
    - 000000002
    ...
```
